/*
 * test_hatari_parity.c - differential test of the host->Atari 8.3 name
 * mapping against Hatari's real implementation.
 *
 * Both functions are linked natively into this binary:
 *
 *   ours    hostfs_host_to_atari()   from $(EMUTOS)/bdos/hostfs_name.c
 *   theirs  Str_Filename_Host2Atari() from $(HATARI)/src/str.c
 *
 * Hatari's str.c is compiled straight out of its own tree with its own
 * headers -- no copy, no transcription, no reimplementation. See
 * hatari_config_stub.c for the single symbol that has to be supplied.
 *
 * A corpus of names is generated by concatenating fragments chosen to
 * hit every branch of both implementations, and every case must agree
 * byte for byte. Any single mismatch fails the run.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ours */
void hostfs_host_to_atari(const char *host, char *out);

/* theirs */
void Str_Filename_Host2Atari(const char *source, char *dst);

/*
 * Fragments. Concatenated 1, 2 and 3 deep, so each fragment gets to be
 * a whole name, a basename, an extension, a middle section, and part of
 * an over-long run.
 */
static const char *const frag[] = {
    "",
    "a",
    "A",
    "z",
    "ab",
    "Ab",
    "abc",
    "TXT",
    "txt",
    "Mixed",
    "readme",
    "abcdefgh",             /* exactly 8 */
    "ABCDEFGHI",            /* exactly 9 */
    "abcdefghijkl",         /* 12 */
    "abcdefghijklmnopqrstuvwxyz0123",   /* 30 */
    "12345678",
    "9",
    ".",
    "..",
    "...",
    "*",
    ":",
    "?",
    "\\",
    "/",
    "\001",                 /* control, low end */
    "\037",                 /* control, byte 31 */
    "\177",                 /* byte 127 */
    "\200",                 /* high byte, low end */
    "\351",                 /* high byte, Atari 'e' with acute */
    "\377",                 /* high byte, top */
    " ",
    "-",
    "_",
    "html",
    "jpeg",
    "bak"
};
#define NFRAG ((int)(sizeof(frag) / sizeof(frag[0])))

/* Names that name a specific rule, kept explicit so a reader can see them. */
static const char *const explicit_cases[] = {
    "",
    ".",
    "..",
    "...",
    "....",
    "a",
    "a.b",
    "a.b.c",
    "x.y.z.w",
    "readme.txt.bak",
    "readme.txt",
    ".bashrc",
    ".config",
    ".a",
    "..a",
    "..ab",
    "..abcd",
    "foo.",
    "foo..",
    "foo...",
    ".foo.",
    "abcdefgh",
    "abcdefghi",
    "abcdefgh.txt",
    "abcdefghi.txt",
    "abcdefgh.t",
    "abcdefghijkl.txt",
    "abcdefghijklmnopqrstuvwxyz0123",
    "abcdefghijklmnopqrstuvwxyz0123.longext",
    "a.html",
    "a.jpeg",
    "a.htmlx",
    "MAKEFILE",
    "Makefile",
    "makefile",
    "AUTO",
    "auto",
    "\200\201\202",
    "\351\351\351.\351\351\351",
    "caf\351.txt",
    "a*b:c?d\\e/f.t?t",
    "\001\002\003.\004\005\006",
    "\177\177.\177",
    "  spaced  .t x",
    "12345678.123",
    "123456789.1234",
    ".......x",
    "a.b.c.d.e.f.g.h.i.j.k",
    "12345678.",
    "1234567.8"
};
#define NEXPLICIT ((int)(sizeof(explicit_cases) / sizeof(explicit_cases[0])))

/* Render a byte string so control and high bytes survive the terminal. */
static void escape(const char *s, char *out, size_t outsz)
{
    size_t n = 0;

    for (; *s; s++)
    {
        unsigned char c = (unsigned char)*s;

        if (n + 5 >= outsz)
            break;
        if (c >= 32 && c < 127)
            out[n++] = (char)c;
        else
            n += (size_t)sprintf(out + n, "\\x%02X", c);
    }
    out[n] = '\0';
}

static long cases_run;
static long mismatches;

static void check(const char *name)
{
    char mine[64], theirs[64];
    char e_in[512], e_mine[512], e_theirs[512];

    memset(mine, 0, sizeof(mine));
    memset(theirs, 0, sizeof(theirs));

    hostfs_host_to_atari(name, mine);
    Str_Filename_Host2Atari(name, theirs);

    cases_run++;

    if (strcmp(mine, theirs) == 0)
        return;

    mismatches++;
    if (mismatches <= 40)
    {
        escape(name, e_in, sizeof(e_in));
        escape(mine, e_mine, sizeof(e_mine));
        escape(theirs, e_theirs, sizeof(e_theirs));
        printf("MISMATCH in=\"%s\"\n         hatari=\"%s\"\n         ours  =\"%s\"\n",
               e_in, e_theirs, e_mine);
    }
    else if (mismatches == 41)
    {
        printf("... further mismatches suppressed\n");
    }
}

/* A few agreed conversions, printed so a run visibly does real work. */
static void show_samples(void)
{
    static const char *const sample[] = {
        "readme.txt", "readme.txt.bak", ".bashrc", "abcdefghijkl.html",
        "a*b:c?d.t?t", "caf\351.TXT", "..", "foo.."
    };
    int i;

    printf("samples (both implementations agree on these):\n");
    for (i = 0; i < (int)(sizeof(sample) / sizeof(sample[0])); i++)
    {
        char out[64], e_in[512], e_out[512];

        memset(out, 0, sizeof(out));
        Str_Filename_Host2Atari(sample[i], out);
        escape(sample[i], e_in, sizeof(e_in));
        escape(out, e_out, sizeof(e_out));
        printf("  %-20s -> %s\n", e_in, e_out);
    }
    printf("\n");
}

int main(void)
{
    int i, j, k;
    char buf[256];

    show_samples();

    for (i = 0; i < NEXPLICIT; i++)
        check(explicit_cases[i]);

    for (i = 0; i < NFRAG; i++)
        check(frag[i]);

    for (i = 0; i < NFRAG; i++)
        for (j = 0; j < NFRAG; j++)
        {
            snprintf(buf, sizeof(buf), "%s%s", frag[i], frag[j]);
            check(buf);
        }

    for (i = 0; i < NFRAG; i++)
        for (j = 0; j < NFRAG; j++)
            for (k = 0; k < NFRAG; k++)
            {
                snprintf(buf, sizeof(buf), "%s%s%s", frag[i], frag[j], frag[k]);
                check(buf);
            }

    /*
     * Dot walked across every position of a fixed run, so the boundary
     * at basename position 8 is hit from both sides with every
     * surrounding length.
     */
    for (i = 0; i < 20; i++)
        for (j = 0; j <= i; j++)
        {
            int n = 0;

            for (k = 0; k < i; k++)
                buf[n++] = (k == j) ? '.' : (char)('a' + (k % 26));
            buf[n] = '\0';
            check(buf);
        }

    /* Every single byte value 1..255, alone and in three positions. */
    for (i = 1; i < 256; i++)
    {
        buf[0] = (char)i;
        buf[1] = '\0';
        check(buf);

        snprintf(buf, sizeof(buf), "ab%cde.f%ch", i, i);
        check(buf);

        snprintf(buf, sizeof(buf), "%cabcdefghi.%cxy", i, i);
        check(buf);

        snprintf(buf, sizeof(buf), "abcdefgh%c.txt", i);
        check(buf);
    }

    printf("hatari parity: %ld cases, %ld mismatches\n", cases_run, mismatches);

    if (mismatches)
    {
        printf("FAIL\n");
        return 1;
    }

    printf("PASS\n");
    return 0;
}
